name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Kontrollo kodin nese ka gabime apo jo
    - uses: actions/checkout@v4

    - name: Build the Docker image and push it to a private repo in DockerHub
      uses: mr-smithers-excellent/docker-build-push@v7
      with:
        image: rigers01/my-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

