name: Expressions-example

on: [push, pull_request_target,]

jobs:
  get-author:
    runs-on: ubuntu-latest
    steps:
      - name: Get the author of the action
        run: echo "The author of the action is ${{github.actor}}"
      - name: Show the Github ref
        run: echo "The Github ref is ${{github.ref}}"
